/*========================================
  Postgres SQL pm inserts for a project 
  ========================================*/ 

set schema 'i2b2pm';

delete from PM_HIVE_DATA where DOMAIN_ID = 'BRISSKIT';

INSERT INTO i2b2pm.PM_HIVE_DATA(domain_id, helpurl, domain_name, environment_cd, active, change_date, entry_date, changeby_char, status_cd)
VALUES ('BRISSKIT','www.brisskit.le.ac.uk','BRISSKIT','DEVELOPMENT',1,now(),now(),'','A');

INSERT INTO i2b2pm.PM_PROJECT_DATA (PROJECT_ID, PROJECT_NAME, PROJECT_WIKI, PROJECT_KEY, PROJECT_PATH, PROJECT_DESCRIPTION, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES ('<SCHEMA_NAME>', '<PROJECT_NAME>', 'http://www.i2b2.org', null, '/<SCHEMA_NAME>', null, now(), now(), null, 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES ('<SCHEMA_NAME>', 'demo', 'DATA_OBFSC', now(), now(), null, 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES ('<SCHEMA_NAME>', 'demo', 'USER', now(), now(), null, 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES('<SCHEMA_NAME>','AGG_SERVICE_ACCOUNT','DATA_AGG', now(), now(), null, 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES('<SCHEMA_NAME>','AGG_SERVICE_ACCOUNT','DATA_OBFSC', now(), now(), null, 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES('<SCHEMA_NAME>','AGG_SERVICE_ACCOUNT','MANAGER', now(), now(), null, 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES('<SCHEMA_NAME>','AGG_SERVICE_ACCOUNT','USER', now(), now(), null, 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES('<SCHEMA_NAME>','demo','DATA_AGG', now(), now(), null, 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES('<SCHEMA_NAME>','demo','ADMIN', now(), now(), null, 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES('<SCHEMA_NAME>','demo','DATA_LDS', now(), now(), null, 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES('<SCHEMA_NAME>','demo','DATA_PROT', now(), now(), null, 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES('<SCHEMA_NAME>','demo','DATA_DEID', now(), now(), null, 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES('<SCHEMA_NAME>','demo','EDITOR', now(), now(), null, 'A');