--------------------------------------------------------
--  DDL for Table SCHEMES
--------------------------------------------------------

  CREATE TABLE SCHEMES 
   (	"C_KEY" VARCHAR(50)	 	NOT NULL,
	"C_NAME" VARCHAR(50)		NOT NULL,
	"C_DESCRIPTION" VARCHAR(100)	NULL,
	 CONSTRAINT SCHEMES_PK PRIMARY KEY(C_KEY)
   ) ;
 
--------------------------------------------------------
--  DDL for Table TABLE_ACCESS
--------------------------------------------------------

  CREATE TABLE TABLE_ACCESS
   (	"C_TABLE_CD" VARCHAR(50)	NOT NULL, 
	"C_TABLE_NAME" VARCHAR(50)	NOT NULL, 
	"C_PROTECTED_ACCESS" CHAR(1)	NULL,
	"C_HLEVEL" INT				NOT NULL, 
	"C_FULLNAME" VARCHAR(700)	NOT NULL, 
	"C_NAME" VARCHAR(2000)		NOT NULL, 
	"C_SYNONYM_CD" CHAR(1)	NOT NULL, 
	"C_VISUALATTRIBUTES" CHAR(3)	NOT NULL, 
	"C_TOTALNUM" INT			NULL, 
	"C_BASECODE" VARCHAR(50)	NULL, 
	"C_METADATAXML" TEXT		NULL, 
	"C_FACTTABLECOLUMN" VARCHAR(50)	NOT NULL, 
	"C_DIMTABLENAME" VARCHAR(50)	NOT NULL, 
	"C_COLUMNNAME" VARCHAR(50)	NOT NULL, 
	"C_COLUMNDATATYPE" VARCHAR(50)	NOT NULL, 
	"C_OPERATOR" VARCHAR(10)	NOT NULL, 
	"C_DIMCODE" VARCHAR(700)	NOT NULL, 
	"C_COMMENT" TEXT	NULL, 
	"C_TOOLTIP" VARCHAR(900)	NULL, 
	"C_ENTRY_DATE" DATETIME		NULL, 
	"C_CHANGE_DATE" DATETIME	NULL, 
	"C_STATUS_CD" CHAR(1)		NULL,
	"VALUETYPE_CD" VARCHAR(50)	NULL,
	CONSTRAINT TABLE_ACCESS_PK PRIMARY KEY(C_TABLE_CD)
   ) ;

   

	

 
